### ISSUE TITLE
[Feature Request] Mean value of temperature to be transmitted instead of noisy actual value

### ISSUE THREAD

**Issue by gon0** [NSPManager/NSPanelManager#111]
The temperature sensor of the panel is not a precise instrument, since the data is quite noisy:
![grafik](https://github.com/NSPManager/NSPanelManager/assets/33236024/b82b8a39-392d-4b82-8541-2e5e44c44c26)

However, after adjusting the temperature offset (https://github.com/NSPManager/NSPanelManager/issues/88), the transmitted temperature value seems to fluctuate around the actual value.

It seems a temperature value is transmitted each 30 seconds:
![grafik](https://github.com/NSPManager/NSPanelManager/assets/33236024/170f722b-8acf-4458-8974-0a832ffcdd4f)

Is there a chance to calculate a mean-value or exponential filter, before the temperature value is sent? I would propose to collect 30 temperature values within 30 seconds (1 value sampled per second) and create the mean value from it. Transmitted is only the mean value, to smooth out fluctuations (if this is not already done).

**Comment by tpanajott** [comment]
Hey!

Thanks for your request and it's something I will definitely look into!

**Comment by tpanajott** [comment]
This will be implemented on the new upcoming beta and forward. Currently implemented but will keep the issue open until it can be tested and verified buy someone more than just me.

**Comment by tpanajott** [comment]
Fixed in latest beta and soon to be stable release.
