### ISSUE TITLE
Upload US tft file results in EU file being uploaded

### ISSUE THREAD

**Issue by cablesandcoffee** [NSPManager/NSPanelManager#117]
Seems like the EU file is being uploaded to the US panel all though "is US panel" is checked in panel settings.
If I upload a new US tft file in the web interface the update screen symbol is shown correctly on the panels which are US panels. But when pressing update screen on the US panel the EU tft ends up on the screen.

**Comment by tpanajott** [comment]
I have confirmed the fix to be working for me. Please test with latest release and close if the issue is solved.

**Comment by cablesandcoffee** [comment]
Works!
