### ISSUE TITLE
Cant change friendly name on panels

### ISSUE THREAD

**Issue by cablesandcoffee** [NSPManager/NSPanelManager#118]
Does not seem to work to change the name on a Panel page. The name does not change on the overview but it does change on the panel page. The panel does not seem to work properly either if you change the name. Upload of firmware, tft file for example does not work until you change it back to the original name.

**Comment by tpanajott** [comment]
Fix pushed to repo. Please try again with latest release and close if fixed.

**Comment by cablesandcoffee** [comment]
Works!
