### ISSUE TITLE
Remove arrows left and right of "ALL" on first page

### ISSUE THREAD

**Issue by cablesandcoffee** [NSPManager/NSPanelManager#121]
Minor gui change. Think someone brought this up in a long GUI-thread or something. I think it would look better to not have the arrows beside the "ALL"-text on first screen. Maybe we should think about removing the text completely when switch to "All Lights"-mode?

**Comment by tpanajott** [comment]
That sounds reasonable. Easy fix.

**Comment by cablesandcoffee** [comment]
Beautiful!
