### ISSUE TITLE
Change Headline on Global Scenes page to Global Scenes

### ISSUE THREAD

**Issue by cablesandcoffee** [NSPManager/NSPanelManager#122]
When entering the Global Scenes page right now it says <--ALL-->. We should probably change that to "Global Scenes" so it is more clear for the user what page they've entered.

**Comment by tpanajott** [comment]
Does it fit in the given space?

**Comment by cablesandcoffee** [comment]
Yes both on EU and US!

**Comment by cablesandcoffee** [comment]
Very nice!
