### ISSUE TITLE
Support for other devices than NSPanel

### ISSUE THREAD

**Issue by bzumik1** [NSPManager/NSPanelManager#126]
Hi I have seen an interesting device based on GT911 namely this one: https://a.aliexpress.com/_EwCtt1n. I can do not know how complicated it would be to add support for that device, but it seems like really nice alternative to NSPanel to those who do not need the physical buttons. I will be glad for any response.

**Comment by tpanajott** [comment]
Hi! Thank you for your comment. You'll have to excuse the delay, I though this issue had been answered.

As the device you linked to is based on the ESP32 the firmware we use should work though that doesn't mean the whole solution will work. Part of the NSPanel is the ESP32, yes, but the other part is the screen itself which isn't just a screen. The screen is a Nextion model which has it's own firmware and serial communication back to the ESP32. So, in short, no, we can't support other models without majorly restructuring the code and introduce a lot of complexity though it would be nice with a cheaper solution. Sorry, maybe in the future when the project has matured more when other higher priority tasks has been handled.
