### ISSUE TITLE
Scene states are not saved (Openhab)

### ISSUE THREAD

**Issue by cablesandcoffee** [NSPManager/NSPanelManager#127]
Scene light states does not seem to be saved. If I go to http://192.168.32.201:8010/api/get_scenes i can se all the scenes that are created but lights_states are all empty.

Example:

1	
scene_id	8
scene_name	"Movie Scene"
room_name	"Livingroom"
room_id	8
light_states	[]

**Comment by tpanajott** [comment]
This should work now, please test and close if fixed.

**Comment by cablesandcoffee** [comment]
Wooo works lite a charm! Nice one! :D
