### ISSUE TITLE
[enhancement] Remotely (via MQTT) change screensaver.

### ISSUE THREAD

**Issue by Ellghe** [NSPManager/NSPanelManager#138]
Basically would I like to shift screen saver mode, having the weather and clock during daytime and only the clock during the night time. (When the alarm is on or off).

**Comment by tpanajott** [comment]
This is now somewhat working though it seems  we need to update the TFT as well. Maybe @cablesandcoffee and chime in with some thoughts? If I change the ssScreensaver variable after the page has been initialized it seems I cant turn on/off the background. Is it possible to fix that within the TFT or do wee need to find an other solution?

**Comment by cablesandcoffee** [comment]
correct, it only ran the code on first load. I've removed the first load function so it will instead run the code every time the page loads. so if the variable has changed the background will change when the page is loaded.

**Comment by tpanajott** [comment]
Confirmed working with new TFT.

**Comment by cablesandcoffee** [comment]
Nice! :)

**Comment by Ellghe** [comment]
My idea was not to chagnge the background but to changer from clock date & weather to only clock!
