### ISSUE TITLE
No way to chose switch in follow mode!

### ISSUE THREAD

**Issue by Ellghe** [NSPManager/NSPanelManager#141]
![image](https://github.com/NSPManager/NSPanelManager/assets/48057939/2aa61db8-a08d-48f3-acd8-ffc422ffad5a)

**Comment by tpanajott** [comment]
Follow mode just means the relay will have the same state as the button. You probably want detached mode.

**Comment by Ellghe** [comment]
Ur right!

**Comment by Ellghe** [comment]
Correct!

**Comment by Ellghe** [comment]
Correct!
