### ISSUE TITLE
No confirmantion of chosen file when upoading TFT-file

### ISSUE THREAD

**Issue by Ellghe** [NSPManager/NSPanelManager#142]
It looks the same as before chosing file.

![image](https://github.com/NSPManager/NSPanelManager/assets/48057939/15253e6e-41ed-4f9b-b269-dd4dffc39a70)

**Comment by tpanajott** [comment]
That's strange. What version are you running? It works for me. Maybe @cablesandcoffee could also have a look?

![image](https://github.com/NSPManager/NSPanelManager/assets/1339738/9d4b1f04-9c44-48c4-85cb-d5d8bebf8468)

**Comment by Ellghe** [comment]
I can se that I was too tired and to ethusiastic to help when writing my observations. After double checking you are right. Suggest that you resize (increase) the text and/or make it black or white in order to make it easier to observe.

**Comment by tpanajott** [comment]
This is now deemed fixed. If you think otherwise, please reopen issue.
