### ISSUE TITLE
Openhab scene shows "save"-icon after editing scene name

### ISSUE THREAD

**Issue by cablesandcoffee** [NSPManager/NSPanelManager#153]
**Describe the bug**
An added scene from Openhab shows the "save" icon to the right after editing the scene name. 

**To Reproduce**
1. Add openhab scene in room in nspanel manager
2. Scene is added with the scene name.
3. Reboot panel, scene is showing on panel, no save icon to the right which is correct
4. Edit the scene name in nspanelmanager, save, reboot panel
5. Scene now shows the save-icon to the right of the scene.

**Expected behavior**
Save icon should not be seen to the right.

**Environment info (please complete the following information):**
 - Openhab
 - NSPanelManager version [0.1.39]
 - NSPanel Firmware version [0.1.91]

**Comment by tpanajott** [comment]
This issue has been fixed. Closing.
