### ISSUE TITLE
NSPanel not connecting to wifi at all

### ISSUE THREAD

**Issue by PixyDon** [NSPManager/NSPanelManager#156]
Hey Guys,

I've followed the Technical Setup installing NSPanel as the addon on Home Assistant and consistently becoming stuck at the wifi configuration section.  I've watched the Cables & Coffee setup video ans well as the Mark Watt Tech video and still the issue persists.  

1. I get to the point where I access the NSPanel wifi access point.
2. Add my HA ip addess as the NSPanel Manager address.
3. Choose from list my SSID and add password.
4. Add MQTT user and password details and click Save.
5. I can see on my wifi router the panel has been picked up.
6. Panel's wifi symbol appears disconnected, doesn't appear in NSPanel Manager.
7. Re-flash and trt again over and over, same result.

 - Home Assistant
 - Chrome
 - 0.1.2.3
 - 0.1.2.5

**Comment by tpanajott** [comment]
What WiFi för you have? Specifically wifi-secutity? We had a user on the discord a few weeks ago that had issues with his WPA3 security as its not really supported. Switching to WPA2 solved it.

**Comment by PixyDon** [comment]
> What WiFi för you have? Specifically wifi-secutity? We had a user on the discord a few weeks ago that had issues with his WPA3 security as its not really supported. Switching to WPA2 solved it.

<img width="847" alt="Screenshot 2024-06-22 at 21 41 14" src="https://github.com/NSPManager/NSPanelManager/assets/3637339/ae871ce5-419b-40f5-8344-56c8238cbb3b">


Seems like split between the 2, I'll see if changing it to WPA2 only helps...

**Comment by PixyDon** [comment]
OK, I'm not sure it has actually do something.  But I now have the following issue, even though adding a room and lights to a room brings up the fill list of entities??

<img width="1701" alt="Screenshot 2024-06-22 at 21 53 56" src="https://github.com/NSPManager/NSPanelManager/assets/3637339/7b306911-81bc-4a8c-8005-6b616495f67f">

**Comment by tpanajott** [comment]
That message comes from the MQTTManager backend component. It says it can't connect to MQTT for whatever reason (have a look in the logs for the addon/container). The list of entities when populating rooms have nothing to do with MQTT. They are gathered directory from Home Assistant and/or OpenHAB. So, your HA connection is working but not MQTT.

**Comment by PixyDon** [comment]
> That message comes from the MQTTManager backend component. It says it can't connect to MQTT for whatever reason (have a look in the logs for the addon/container). The list of entities when populating rooms have nothing to do with MQTT. They are gathered directory from Home Assistant and/or OpenHAB. So, your HA connection is working but not MQTT.

Thanks, I hadn't created an MQTT User and had used the default homeassistant usr/pwd.

Added a user and re-flashed, went through setup again and it seems to be working now.  Just need to get the screen updated...
