### ISSUE TITLE
Openhab Items are not shown when editing a light

### ISSUE THREAD

**Issue by cablesandcoffee** [NSPManager/NSPanelManager#159]
**Describe the bug**
Openhab Things are not shown when editing a light

**To Reproduce**
1. Go to room page, edit a light
2. Pop up does not show the Openhab Items that are connected to that light

**Expected behavior**
When editing a light the Items chosen when adding the light should be seen.

**Screenshots**
![Screenshot from 2024-07-26 23-07-49](https://github.com/user-attachments/assets/abb40d40-ffac-445f-80d1-6c338f87dac4)

**Environment info (please complete the following information):**
 - Openhab
 - Firefox
 - NSPanelManager version [0.1.42]

**Additional context**

**Comment by tpanajott** [comment]
With the new way entities are gathered (the can be filtered) there was one place were a filter was not sent along and therefore didn't get any items from OpenHAB. Confirmed the issue and fixed. Closing.
