### ISSUE TITLE
NSPanel Manager Scenes Functionality

### ISSUE THREAD

**Issue by cablesandcoffee** [NSPManager/NSPanelManager#16]
I think there could be two user solutions for scenes. Number 1 is the primary, nr 2 is nice but personally not a need. 

**1.** For people that don't have scene solutions or think our solution is an easier way of working with scenes.
There should be both **Room Scenes** and **Home Scenes**. Room Scenes saves light states for lights in a specific room. Home Scenes saves light states for all lights in the home.

In NSPanel Manager user should be able to name up to 4 room scenes/room and total of 4 home scenes.
These should populate when user accesses the panels room scene page or home scene page which will consist of the scenes, a save button and and activate button.

When pressing save all current lights states in room/home will be saved to NSPanel Manager database. 
Pressing On Scene Name will collect the values from database and send it on the HA/OH websocket.

**Topic to activate from outside**
Scenes created with number 1 solution should have a nice topic so that it is easy to activate the scene from HA/OH (maybe by voice) if user wants that ability. 

**2.** For people who already have scene solutions set up in there smart home that they want to keep using.
In this case the user should be able to call there scenes from the panel. Similar to adding lights to rooms they add there scenes to the scene page. If they have some kind of save switch, the could add this as well and all we would do would be to turn ON/OFF the exposed HA/OH switch.

**Comment by tpanajott** [comment]
I'm thinking that an implementation of this would be that all NSPM scenes could call on external scenes. This would make it possible to configure an empty scene that would just call a separate scene in Home Assistant or OpenHAB. Either that or simply that there are two modes. 

### 1.
Scenes are handled by NSPM
### 2.
Connect the button for "scene 2" to a scene in Home Assistant/OpenHAB and have it trigger it. This would mean that you don't have to create "dummy"-scenes in order to trigger scenes already setup.

**Comment by cablesandcoffee** [comment]
Yes I think there should be 2 options as you say. 

1 is for users not having any scene solution set up. This would be an easy way to get it.

2 is for users already having some kind of scene solution. An example could be users using zigbee2mqtt scene solution with an activate/save switch. Those users could add their Activate/Save switches just like Lights are added to the panel using the API.

**Comment by tpanajott** [comment]
@cablesandcoffee it would be great to be able to display/hide the "Save"-icon on the Scenes-page as they are currently now always shown. Am I missing something or are they not controllable/defined in the firmware?

**Comment by cablesandcoffee** [comment]
That is true, I will fix that. Plan forward is to have icons on all similar buttons instead of the way I've done it before. It's easier now when it's a solid background color.

**Comment by cablesandcoffee** [comment]
Long time since we wrote anything here. The icon stuff that you mentioned in July is obviously fixed now. From or initial plan for this functionality the only thing left would be the ability to activate a scene currently existing in HA or OH. Maybe we could close this one and open a new one that is more specific to that and we can discuss when and if we still want/need that feature?

**Comment by tpanajott** [comment]
> Long time since we wrote anything here. The icon stuff that you mentioned in July is obviously fixed now. From or initial plan for this functionality the only thing left would be the ability to activate a scene currently existing in HA or OH. Maybe we could close this one and open a new one that is more specific to that and we can discuss when and if we still want/need that feature?

The feature to activate scenes in OpenHAB and Home Assistant is now available in the beta and soon to become stable, will close.
