### ISSUE TITLE
Changing from C to F on weather page does not fully work on first page of web interface

### ISSUE THREAD

**Issue by cablesandcoffee** [NSPManager/NSPanelManager#161]
**Describe the bug**
Changing from C to F on weather page does not fully work on first page of web interface

**To Reproduce**
1. Go to weather page
2. Change from C to F, press save.
3. Go to first page
4. C has changed to F on each panel summary
5. Reboot a panel
6. Temperature value should now be in F but is still in C but with the letter F beside

**Expected behavior**
Temp value should be in F

**Environment info (please complete the following information):**
 - Firefox
 - NSPanelManager version [ 0.1.42-public_beta ]
 - NSPanel Firmware version [0.1.97]

**Comment by tpanajott** [comment]
Issue confirmed and fixed. Closing.
