### ISSUE TITLE
Scene creation allow more than 4 scenes

### ISSUE THREAD

**Issue by cablesandcoffee** [NSPManager/NSPanelManager#162]
**Describe the bug**
Panel GUI can only show four scenes/room
Manager lets you create more than four

**Expected behavior**
Only allow four to be created

**Comment by tpanajott** [comment]
Buttons to add/create new NSPM scene are no longer shown when 4 scenes are created/assigned to a room. Instead an info-alert is shown stating that only 4 scenes can be assigned per room. Please verify and close if deemed fixed.

**Comment by cablesandcoffee** [comment]
Works, nice!
