### ISSUE TITLE
Change "Update screen" choice to "Update GUI"

### ISSUE THREAD

**Issue by cablesandcoffee** [NSPManager/NSPanelManager#163]
Today it says "GUI update available" to alert user that there if a new tft file to be uploaded.
To upload user has the option to press Update Screen.

Change naming to be more consistent user friendly.

I propose "GUI update available" and "Update GUI"

**Comment by cablesandcoffee** [comment]
Saw that you changed this. I think we should also change the text when you update GUI on all panels from the Actions-button.

**Comment by tpanajott** [comment]
Ah, missed a place. Will fix.

**Comment by tpanajott** [comment]
Should be all fixed as of now.
