### ISSUE TITLE
Popup Weather & Temperature location selection not always shown 

### ISSUE THREAD

**Issue by ehoberg** [NSPManager/NSPanelManager#166]
**Description**

The second time the popup should be shown when pressing "Search", the popup is not shown.

**To Reproduce**
1. Go to Entities --> Weather & Time
2. Go to the group "Weather & Temperature"
3. Click on "Search" in Latitude or Longitude
4. Close the popup.
5. Click on "Search" in Latitude or Longitude --> Popup is not shown anymore

Alternative method:
1. Go to Entities --> Weather & Time
2. Go to the group "Weather & Temperature"
3. Click on "Select" in "Outside temperature sensor"  <-- This popup always functions.
4. Close the popup
5. Click on "Search" in Latitude or Longitude --> Popup is not shown

**Expected behavior**
Popup should always be shown

**Screenshots**
Not relevant. 

**Environment info (please complete the following information):**
 - Home Assistant 
 - Chrome/Brave
 - NSPanelManager version    :  0.1.43-public_beta_h2
 - NSPanel Firmware version  : Not relevant, its a small NSPanelManager GUI bug.

**Additional context**

**Comment by tpanajott** [comment]
This issue should be fixed as of lats commit but I will keep it open until next release.
