### ISSUE TITLE
Add default light value when 0

### ISSUE THREAD

**Issue by ehoberg** [NSPManager/NSPanelManager#167]
**Is your feature request related to a problem? Please describe.**
When the light value of the main slider is at 0, the toggle button for individual light control will act like it does nothing. 

**Describe the solution you'd like**
Initially force the light to 50% when turn on at 0 is requested. Later, if desired, finer grained control can be implemented such as a global default, or per room default. This way the toggle button will respond normally. 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by tpanajott** [comment]
As per @damiendep on Discord this also affect detached lights which is not surprising as they follow exactly the same logic.

**Comment by tpanajott** [comment]
This issue is closed as per latest commit. Will keep issue open until we push a new public beta release. Thanks for reporting!
