### ISSUE TITLE
Update tft file weather page default values

### ISSUE THREAD

**Issue by cablesandcoffee** [NSPManager/NSPanelManager#170]
Right now there are random values and icons on the weather page left from building and testing the page in Nextion editor.
Remove random numbers in nextion editor and set same default icons everywhere so it looks clean if the weather does not load or takes a couple of seconds to load.

**Comment by tpanajott** [comment]
Perhaps it would be a good idea to somehow indicate that data is missing? A special icon? Perhaps default temperature is 255 or something totalt unreasonable?

**Comment by cablesandcoffee** [comment]
Yes I have a plan! m thinking just a hyphen for the numbers which indicated data is missing. And for the icons we have a supernice weather icon with an exclamation mark! :)

**Comment by cablesandcoffee** [comment]
![mdi--weather-cloudy-alert(2)](https://github.com/user-attachments/assets/99a9e857-71fa-4df5-8d38-148a7b423f6d)

**Comment by cablesandcoffee** [comment]
Fixed. Closing
