### ISSUE TITLE
[Bug] URL manager not showed

### ISSUE THREAD

**Issue by mainmind83** [NSPManager/NSPanelManager#173]
Missing administrator URL and port with new firmware (not migrated)

1. Update firmware to 0.1.150
2. Visit Website of panel
3. Manager address show  -- UNKNOW TEMPLATE -- 
4. Manager port (blank)

![image](https://github.com/user-attachments/assets/b4bcaec2-35e6-4b70-a110-5f7b90b63946)

**Environment info:**
 - Home Assistant 2024.8.3
 - Chrome
 - NSPanelManager version 1.0.0
 - NSPanel Firmware version 0.1.150

**Comment by tpanajott** [comment]
Yhea, ignore that. This happens because it has updated the firmware and not littlefs. Try updating the firmware again and make sure you have updated your addon/container.

**Comment by mainmind83** [comment]
Mmm I have tried to set the value and save the values, now the panels appear offline on manager...

**Comment by tpanajott** [comment]
Did you set the manager address and port in the manager?

**Comment by mainmind83** [comment]
Yes, of course... i updated from previuos version, HA show wizard en updating too...

**Comment by tpanajott** [comment]
Okay, just double checking. Do you have logging enabled on the panel?

**Comment by tpanajott** [comment]
You should be able to see logs from the panel in the manager given you have logging turned on on the panel. Otherwise, reboot the panel and in the web interface you showed in the picture above set the log level to debug.

**Comment by mainmind83** [comment]
![image](https://github.com/user-attachments/assets/74af7683-5d72-4b8a-9c31-a9ee6badc5d1)

![image](https://github.com/user-attachments/assets/6261d9a4-0ebd-4593-bbd4-66cb9653f4ad)

Not showed protocol versión... not showed log...

**Comment by mainmind83** [comment]
![image](https://github.com/user-attachments/assets/16bd84c6-e2b5-4f0b-8598-493f11d7d2d1)

There is some problem when retrieving the data, I have set everything again (including MQTT password) which seems not to be correct when reloading the interface text box
NOTE: I think I remember that I reported a similar bug in the previous version... I'm going to look

**Comment by mainmind83** [comment]
After re-entering the MQTT password, the configuration has been saved, I have updated the firmware again (second time) and now the v0.1.150 website does look like the new one (different options and blue background), I am updating TFT...

![image](https://github.com/user-attachments/assets/9d9833ca-80d1-4961-9925-ec0429a0a092)

**Comment by tpanajott** [comment]
Nice progress. Denna like you are getting somewhere!

**Comment by mainmind83** [comment]
I had deleted browser cache, private mode... in testing.

It should not be necessary to send the firmware twice to the device for it to update the web interface completely...

**Comment by tpanajott** [comment]
That's a known bug we had previously that's been fixed. It shouldn't happen again.

**Comment by mainmind83** [comment]
Fixed, if anyone else has this problem:

1.- Enter the panels website and enter the data again ([including the MQTT server password information](https://github.com/NSPManager/NSPanelManager/issues/82))
2.- Restart NSPanelManager
3.- Send firmware update again
4.- Update TFT
