### ISSUE TITLE
Add info on flashing with esphome web ui to Documentation

### ISSUE THREAD

**Issue by cablesandcoffee** [NSPManager/NSPanelManager#197]
Just adding this to remind myself of doing this. I just remembered I forgot to do this...

**Comment by MrFloppy** [comment]
Maybe you can give me a hint on how to do that? :D

**Comment by tpanajott** [comment]
> Maybe you can give me a hint on how to do that? :D

Well, you shouldn't have to any more. This is implemented in the new documentation [page](https://nspanelmanager.com/).

@cablesandcoffee perhaps this issue can be closed?

**Comment by cablesandcoffee** [comment]
@tpanajott yes correct! Closing!
