### ISSUE TITLE
Temperature always shows in Celsius.

### ISSUE THREAD

**Issue by aaronouthier** [NSPManager/NSPanelManager#199]
**Describe the bug**
Neither the NSPManager, not the individual Panels seem to have a way to change temp to Fahrenheit. 

**Expected behavior**
A way to set displayed indoor temp to Fahrenheit.

**Screenshots**
N/A

**Environment info (please complete the following information):**
 - Home Assistant
 - Safari on Apple iPad running iPadOS 18.
 - NSPanelManager version 0.1.46 beta.
 - Unable to check.

**Comment by tpanajott** [comment]
Hi, this is send under "Entities" -> "Weather and time"

**Comment by aaronouthier** [comment]
Ok, that worked! It used to be in the settings menu. I got thrown off.
