### ISSUE TITLE
New documentation widget: beta

### ISSUE THREAD

**Issue by sebastienvermeille** [NSPManager/NSPanelManager#210]
**Is your feature request related to a problem? Please describe.**
As discussed per slack it would be great to have the possibility to flag the features available only in the beta firmware.

**Describe the solution you'd like**
As a baby step, I propose to create a beta label (same as what we have for labels in GitHub issues/pr)

**Describe alternatives you've considered**
We could have a doc versioned per version/tag but at this stage, I don't think it's so valuable. The project has only "one released version" and a "v2" on the road. We might consider this when we release V2. (Both are not incompatible)

**Additional context**
I will open a PR including some screenshots for this so we get a better vision.

**Comment by tpanajott** [comment]
Closing this issue as #211 has been accepted and merged.
