### ISSUE TITLE
Broken "ADD ADD-ON REPOSITORY TO MY" link on documentation

### ISSUE THREAD

**Issue by astritzeqiri** [NSPManager/NSPanelManager#215]
**Describe the bug**
The link under the [docs](https://nspanelmanager.com/docs/getting-started/install/installation-guide-home-assistant/) to install the add-on to homeassistant is broken.

**To Reproduce**
1. Go to https://nspanelmanager.com/docs/getting-started/install/installation-guide-home-assistant/
2. Click on "ADD ADD-ON REPOSITORY TO MY"
3. Click open link.
4. See the broken link on the input field -> https://github.com/NSPanelManager%2NSPManager

**Expected behavior**
The link should be https://github.com/NSPManager/NSPanelManager

**Screenshots**
![image](https://github.com/user-attachments/assets/04f588e0-4bd3-4005-a126-abaa5e1a142e)

**Environment info (please complete the following information):**
 - Home Assistant user

**Comment by tpanajott** [comment]
Thank you for your contribution, PR is merged.
