### ISSUE TITLE
Add choice on physcial buttons for user to send a custom mqtt command

### ISSUE THREAD

**Issue by cablesandcoffee** [NSPManager/NSPanelManager#37]
Right now users can choose from Direct mode or Detached mode. There can be users that want to trigger for example their coffee brewer with one of the buttons on just one panel. Add functionality to send a custom mqtt message to allow the user to trigger what ever they want.

**Comment by tpanajott** [comment]
Functionality added in latest merge, closing.

**Comment by Roukie686868** [comment]
I love the MQTT option under the buttons. Works great
