### ISSUE TITLE
IP address on boot screen.

### ISSUE THREAD

**Issue by Roukie686868** [NSPManager/NSPanelManager#67]
While the unit boots up and connects to the manager it would be nice to have the IP address shown shortly.

**Comment by tpanajott** [comment]
Perhaps @cablesandcoffee could update the TFT to include a secondary info-box on the boot screen?

**Comment by Roukie686868** [comment]
Would be great. Due to some circumstances I have more than one DHCP server in my network. On a reboot of a panel it often gets a new IP address. The NSPanelManager has seems to have issue with that as it takes some time to change the redirect (IP address) to the panel page. When the boot screen shows the latest IP I can get there manually.

**Comment by tpanajott** [comment]
I don't think the manager would automatically update the IP-addreas of the panel but you would have to make a manual refresh or the web page but I would think you already tried that.

**Comment by Roukie686868** [comment]
I think the panel went back to the old IP address and so the link worked again. I got to find the time to fix my multiple DHCP problem. Went all works well there is very little need to go the the panel web page anyway.

**Comment by tpanajott** [comment]
Yhea, the whole idea is that you change settings on the panel once when you set it up and then don't have to touch it again. That doesn't excuse this bug though, it should still work.

**Comment by cablesandcoffee** [comment]
Yes will add this to my todo list!

**Comment by cablesandcoffee** [comment]
Did some work on the GUI and happened to remember this one so I've just added a text box on the bootscreen to be able to print out panel ip address. Updated tftdefines files with info on the textbox.

**Comment by cablesandcoffee** [comment]
This works, closing! :D
