### ISSUE TITLE
Delete dummy room - lose NSPanel. 

### ISSUE THREAD

**Issue by velijv** [NSPManager/NSPanelManager#69]
1. Create real rooms
2. Delete Dummy room (where NSPanel is)
3. No NSPanel anymore :( 
4. Plugging it out and in brought it back to the first room luckily.

**Comment by tpanajott** [comment]
Thea, perhaps it's better to move the panel to the next available room instead of simply removing the panel when removing the room. Should be an easy fix once I get the time to look at it.

**Comment by tpanajott** [comment]
Fixed in commit d97e19d5b7acd6c7843e239dc560aa245865f995
