### ISSUE TITLE
Rename panel loses some connection

### ISSUE THREAD

**Issue by frontfoto** [NSPManager/NSPanelManager#70]
When I change the name on the device in the manager the nspanel reboots but then shows offline. Even though it's reachable with the ip and can be controlled. If I remove the panel from manager it reboots and then it connects and shows online even though I need to configure it again.

**Comment by tpanajott** [comment]
Where did you rename the panel and how did you do it? It has to be renamed in the manager and then the panel itself has to be rebooted for it to take affect.

**Comment by frontfoto** [comment]
Unsure if I renamed it in manager or on the panels individual page. On one of this pages. I might have been on panels individual page. It didn't create a new panel in software and the link to the panels page still worked even though the manager listed it as offline.

**Comment by mainmind83** [comment]
May be related to: https://github.com/NSPManager/NSPanelManager/issues/79

**Comment by tpanajott** [comment]
This issue should never happen with the new upcoming stable release of the rewrite of the manager. Closing this issue.
