### ISSUE TITLE
[Bug] "Unknow status" on NSPanel-EU after rename panel

### ISSUE THREAD

**Issue by mainmind83** [NSPManager/NSPanelManager#79]
It's possible connecto to NSPanel IP, manager show dBm, ºC, % CPU... but always show "unknow status", when trying send TFT file with "Update screen" not show progress...

![image](https://github.com/NSPManager/NSPanelManager/assets/18678468/b3f901e5-806b-4861-bfda-6cd9873b2ad8)

The manual does not show help on the options "[upload new tft file](https://github.com/NSPManager/NSPanelManager/tree/main/docker/web/nspanelmanager)", "upload new data file"...

**Comment by tpanajott** [comment]
Can you make sure the panel has connected to mqtt? There is unfortunately no indicator on the panel or in the web interface so you will have to check your MQTT broker.

**Comment by mainmind83** [comment]
Ohh, when you change name of panel, not updated name on MQTT, I delete with MQTT Explorer and from Manager and add again, now its working ;)

**Comment by tpanajott** [comment]
Oh, interesting bug. I'm currently reworking the handshake and backend of the container so this procedure will change in the future so hopefully this bug will not show up again.

**Comment by mainmind83** [comment]
When the name of the panel is changed, the name of the associated HA entities does not change either.

**Comment by tpanajott** [comment]
That's strange as it should send the updated name to HA but it might be that HA is not updating the already registered entity. Will have to check that.

**Comment by tpanajott** [comment]
This is fixed in the latest beta release and in the upcoming stable based on the beta. Will close.
