### ISSUE TITLE
[Enhancement] Temperature calibration/offset

### ISSUE THREAD

**Issue by mainmind83** [NSPManager/NSPanelManager#88]
Allows you to set an offset value or include temperature sensor calibration directly on the panel

**Comment by tpanajott** [comment]
There is a way to set an offset in the panel specific settings page in the manager. See section 3.2 in the manual.

**Comment by mainmind83** [comment]
I was looking at the general settings instead of the panel settings, my bad, sorry

![image](https://github.com/NSPManager/NSPanelManager/assets/18678468/af6da02b-f828-4beb-9a82-b46c5b3e686f)

**Comment by tpanajott** [comment]
No worries, glad you found it 😀
