### ISSUE TITLE
error message in live log

### ISSUE THREAD

**Issue by stleusc** [NSPManager/NSPanelManager#92]
```
03:10:16 | ERROR | LightManager.cpp:341 f(._taskProcessMqttMessages) Got state update for unknown attribute: state_hue
03:10:15 | ERROR | LightManager.cpp:341 f(._taskProcessMqttMessages) Got state update for unknown attribute: state_sat
```
Using home assistant, lastest version, installed via HA AddOn.
Currently added a single light that support RGB and color temp.

**Comment by tpanajott** [comment]
Yup, known bug though I don't think it has been reported here previously. Basics, RGB control from the panel works but it won't receive new RGB values from HA/OpenHAB or other panels.
